### ISSUE TITLE
:qb type object fails to initialize 

### ISSUE THREAD

**Issue by rposborne** [qbwc/quickbooks_api#2]
require "Quickbooks"

api = Quickbooks::API.instance(:qb)  

if you initialize a qbpos object it will complete the load.   But it appears to be incomplete, stoping short at SpecialAccountAdd.

[Quickbooks::QBXML::QBXML, Quickbooks::QBXML::QBXMLMsgsRq, Quickbooks::QBXML::HostQueryRq, Quickbooks::QBXML::IncludeListMetaData, Quickbooks::QBXML::CompanyQueryRq, Quickbooks::QBXML::CompanyActivityQueryRq, Quickbooks::QBXML::PreferencesQueryRq, Quickbooks::QBXML::AccountAddRq, Quickbooks::QBXML::AccountAdd, Quickbooks::QBXML::ParentRef, Quickbooks::QBXML::SalesTaxCodeRef, Quickbooks::QBXML::AccountModRq, Quickbooks::QBXML::AccountMod, Quickbooks::QBXML::AccountQueryRq, Quickbooks::QBXML::NameFilter, Quickbooks::QBXML::NameRangeFilter, Quickbooks::QBXML::SpecialAccountAddRq, Quickbooks::QBXML::SpecialAccountAdd]

/Users/rposborne/.rvm/gems/ruby-1.9.2-p290@lumber/gems/quickbooks_api-0.1.4/lib/quickbooks/parser/class_builder.rb:27:in `add_casting_attribute': undefined method`call' for nil:NilClass (NoMethodError)
    from /Users/rposborne/.rvm/gems/ruby-1.9.2-p290@lumber/gems/quickbooks_api-0.1.4/lib/quickbooks/dtd_parser.rb:9:in `process_leaf_node'
    from /Users/rposborne/.rvm/gems/ruby-1.9.2-p290@lumber/gems/quickbooks_api-0.1.4/lib/quickbooks/qbxml_parser.rb:37:in`process_xml_obj'
    from /Users/rposborne/.rvm/gems/ruby-1.9.2-p290@lumber/gems/quickbooks_api-0.1.4/lib/quickbooks/qbxml_parser.rb:32:in `process_xml_obj'

**Comment by skryl** [comment]
Looks like something I broke not long ago. I hope to actually write some tests in the near future :)

I wrote this api wrapper specifically to work with QBPOS so it hasn't been tested with Quickbooks Financial whatsoever. It should theoretically work just fine but let me know how it goes and Ill do all I can to help.

Alex

**Comment by rposborne** [comment]
I can't hug you at the moment so PayPal is going to have to suffice.   Is your github email your paypal email?

**Comment by skryl** [comment]
It is. Thank you very much.
